### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'init_cfg'

### ISSUE THREAD

**Issue by tuxiangxianzhe** [Eli-YiLi/WSSS_MMSeg#1]
Traceback (most recent call last):
  File "tools/train.py", line 161, in <module>
    main()
  File "tools/train.py", line 131, in main
    cfg.model, train_cfg=cfg.train_cfg, test_cfg=cfg.test_cfg)
  File "/space0/yisheng/workspace/WSSS_MMSeg/mmseg/models/builder.py", line 57, in build_segmentor
    return build(cfg, SEGMENTORS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/space0/yisheng/workspace/WSSS_MMSeg/mmseg/models/builder.py", line 32, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/space0/yisheng/anaconda3/envs/py37pt110/lib/python3.7/site-packages/mmcv/utils/registry.py", line 171, in build_from_cfg
    return obj_cls(**args)
  File "/space0/yisheng/workspace/WSSS_MMSeg/mmseg/models/segmentors/encoder_decoder.py", line 37, in __init__
    self.backbone = builder.build_backbone(backbone)
  File "/space0/yisheng/workspace/WSSS_MMSeg/mmseg/models/builder.py", line 37, in build_backbone
    return build(cfg, BACKBONES)
  File "/space0/yisheng/workspace/WSSS_MMSeg/mmseg/models/builder.py", line 32, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/space0/yisheng/anaconda3/envs/py37pt110/lib/python3.7/site-packages/mmcv/utils/registry.py", line 171, in build_from_cfg
    return obj_cls(**args)
TypeError: __init__() got an unexpected keyword argument 'init_cfg'

Hello, this is my error message, it seems that the mmcv doesn't include argument 'init_cfg' in 1.1.4.
If you have changed mmcv?

**Comment by Eli-YiLi** [comment]
What's the version of mmseg? My version is 0.8.0
It may be that mmcv and mmseg are incompatible.

**Comment by tuxiangxianzhe** [comment]
0.8.0
In fact, I git clone your mmseg part code and use "python setup.py develop" to install, and the version is 0.8.0, as same as you said.

**Comment by Eli-YiLi** [comment]
what's your run command, and which config do you use.

**Comment by Eli-YiLi** [comment]
OK, configs for coco have problems in config
(I try to use a new version but failed, and I forget to roll back for these configs)
please wait and pull after update.

**Comment by Eli-YiLi** [comment]
Done
